JustCode\Bundle\actividadesBundle\Entity\Preguntas:
    type: entity
    table: Preguntas
    indexes:
        fk_Preguntas_Niveles1_idx:
            columns:
                - Niveles_idNiveles
    id:
        idpreguntas:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idPreguntas
    fields:
        enunciado:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
    oneToOne:
        nivelesniveles:
            targetEntity: Niveles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Niveles_idNiveles:
                    referencedColumnName: idNiveles
            orphanRemoval: false
    lifecycleCallbacks: {  }
