JustCode\Bundle\actividadesBundle\Entity\Respuestas:
    type: entity
    table: Respuestas
    indexes:
        fk_Respuestas_Preguntas_idx:
            columns:
                - Preguntas_idPreguntas
        fk_Respuestas_Niveles1_idx:
            columns:
                - Niveles_idNiveles
    id:
        idrespuestas:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idRespuestas
    fields:
        textoRespuesta:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
            column: texto_respuesta
        correcta:
            type: boolean
            nullable: true
    oneToOne:
        preguntaspreguntas:
            targetEntity: Preguntas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Preguntas_idPreguntas:
                    referencedColumnName: idPreguntas
            orphanRemoval: false
        nivelesniveles:
            targetEntity: Niveles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Niveles_idNiveles:
                    referencedColumnName: idNiveles
            orphanRemoval: false
    lifecycleCallbacks: {  }
