<?php

namespace Proxies\__CG__\JustCode\Bundle\actividadesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Preguntas extends \JustCode\Bundle\actividadesBundle\Entity\Preguntas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'JustCode\\Bundle\\actividadesBundle\\Entity\\Preguntas' . "\0" . 'idpreguntas', '' . "\0" . 'JustCode\\Bundle\\actividadesBundle\\Entity\\Preguntas' . "\0" . 'enunciado', '' . "\0" . 'JustCode\\Bundle\\actividadesBundle\\Entity\\Preguntas' . "\0" . 'nivelesniveles'];
        }

        return ['__isInitialized__', '' . "\0" . 'JustCode\\Bundle\\actividadesBundle\\Entity\\Preguntas' . "\0" . 'idpreguntas', '' . "\0" . 'JustCode\\Bundle\\actividadesBundle\\Entity\\Preguntas' . "\0" . 'enunciado', '' . "\0" . 'JustCode\\Bundle\\actividadesBundle\\Entity\\Preguntas' . "\0" . 'nivelesniveles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Preguntas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpreguntas($idpreguntas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpreguntas', [$idpreguntas]);

        return parent::setIdpreguntas($idpreguntas);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpreguntas()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpreguntas();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpreguntas', []);

        return parent::getIdpreguntas();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnunciado($enunciado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnunciado', [$enunciado]);

        return parent::setEnunciado($enunciado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnunciado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnunciado', []);

        return parent::getEnunciado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelesniveles(\JustCode\Bundle\actividadesBundle\Entity\Niveles $nivelesniveles = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelesniveles', [$nivelesniveles]);

        return parent::setNivelesniveles($nivelesniveles);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelesniveles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelesniveles', []);

        return parent::getNivelesniveles();
    }

}
