<?php
namespace JustCode\Bundle\actividadesBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelesRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM actividadesBundle:Niveles p ORDER BY p.name ASC')
            ->getResult();
    }
}