<?php
namespace JustCode\Bundle\actividadesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntasRepository extends EntityRepository
{


    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM actividadesBundle:Preguntas p ORDER BY p.name ASC')
            ->getResult();
    }


}